name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'
    - run: make
